language: node_js

services:
  - docker

script:
  - docker-compose build

before_install:
  - sudo apt-get update
  - docker ps
  - sudo service postgresql stop

after_success:
  - docker images
  - docker info
  - docker login -u _ -p "$HEROKU_TOKEN"  registry.heroku.com
  - docker tag core-api:latest registry.heroku.com/micro-teste/web
  - docker push registry.heroku.com/micro-teste/web
