language: node_js

services:
  - docker

script:
  - docker-compose up --build

before_install:
  - sudo apt-get update
  - docker ps
  - sudo service postgresql stop

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: docs
  on:
    branch: stable
