language: node_js

services:
  - docker

script:
  - docker-compose build

before_install:
  - sudo apt-get update
  - docker ps

deploy:
  provider: Heroku
  api_key: $HEROKU_TOKEN
  app: micro-teste
  on:
    branch: sprint3/ci-cd
  run:
    - npm run typeorm -- migration:run
