language: node_js

services:
  - docker

before_install:
  - sudo apt-get update
  - docker ps
  - docker-compose build

script: bash deploy.sh

deploy:
  provider: script
  on:
    branch: sprint3/ci-cd
